window.SITE_CONTENT = Object.freeze({
  profile: {
    name: "老洛MMO",
    specialty: "歌颂者 PVP / GVG / PVE 实战攻略",
    avatar: "assets/laoluo-avatar.jpg",
    shortBio: "专注歌颂者的图文实战判断、连招整理与 PVP / GVG / PVE 对局归档。",
    wechat: "Zephyrus1122",
  },
  version: {
    label: "公测首月版本",
    detail: "游戏官网当前下载信息为 Android 客户端 1.1.1、PC 启动器 1.1.43.0；不同平台编号不可互换。本站攻略按 9月初老四 / 老五团本与 64装等三件套阶段整理，最后核验于 2026年9月7日。",
  },
  platforms: [
    { name: "抖音", url: "https://v.douyin.com/MpvBDv7fusA/", note: "老洛MMO 抖音主页" },
    { name: "哔哩哔哩", url: "https://b23.tv/qdxbCnM", note: "老洛MMO B站主页" },
  ],
  guides: [
    {
      id: "field-manual",
      title: "歌颂者序列 8 PVP GVG攻略",
      summary: "整理序列 8 阶段的天赋、装备、属性、防御、技能组、封印物与秘偶选择，并补充小号 GVG 的成型思路。",
      tags: ["PVP", "GVG"],
      status: "已发布",
      updated: "2026年9月7日发布｜9月7日核验",
      featured: true,
      url: "guide-singer-pvp-gvg.html",
      comboIds: ["pvp-combo-ready"],
      article: {
        intro: "本攻略面向准备参与 PVP 与 GVG 的歌颂者序列 8 玩家，重点整理天赋、装备、属性、技能组、封印物和秘偶的选择。先按自身面板补齐短板，再根据战斗规模调整技能组。",
        published: "2026年9月7日",
        applicability: "序列 8｜PVP / GVG",
        sections: [
          {
            id: "talents",
            title: "天赋点",
            lead: "先完成序列 8 的扮演任务，再按自身面板选择有效属性更多的天赋节点。",
            image: "assets/singer-sequence8-pvp-gvg-01.webp",
            imageAlt: "歌颂者序列 8 非凡天赋界面截图，展示圣裁分支",
            caption: "原攻略配图：序列 8 非凡天赋推荐方案。",
            blocks: [
              { title: "先完成序列 8 扮演任务", text: "序列 8 开放后，先把序列 8 的扮演任务完成到 20%，拿够天赋点。当前阶段已经可以调整属性，不必再只看哪个节点分数高就带哪个。" },
              { title: "按面板短板选择节点", text: "点天赋前，先查看自身穿刺和格挡，优先补三项属性中更低的一项。还要注意目标属性在三个天赋节点中的排序：如果需要的属性排位较低，说明该节点提供的有效属性较少，换一个节点即可。" },
            ],
          },
          {
            id: "equipment",
            title: "装备选择",
            lead: "64 装等阶段先把独珍三件套穿齐，再根据面板补关键属性。",
            image: "assets/singer-sequence8-pvp-gvg-02.webp",
            imageAlt: "歌颂者序列 8 PVP 角色面板与装备方案截图",
            caption: "原攻略配图：序列 8 PVP 角色面板与装备方案。",
            blocks: [
              { title: "优先穿齐独珍三件套", text: "64 装等装备已经拿到不少时，优先把独珍三件套全部穿上，再根据自身面板补齐属性。装备选择的第一目标是让关键属性达标，不要为了单件装备的分数牺牲整体配置。" },
            ],
          },
          {
            id: "stats",
            title: "属性与防御方向",
            lead: "圣光进化提高增伤，穿刺与格挡按面板短板补齐，先满足 PVP / GVG 的实战阈值。",
            blocks: [
              { title: "圣光进化与增伤", text: "序列 8 开启圣光进化后，会获得额外 5% 增伤效果。暴击和穿刺的提升，会根据自身面板按比例放大，因此面板越高，进化带来的收益越明显。" },
              { title: "穿刺目标", text: "序列 8 打 PVP / GVG 不必把穿刺堆得过高，1800 以上即可；配合 buff 后，轻松达到约 2500，穿刺率可达到 80% 以上。" },
              { title: "格挡与技能抵挡", text: "今天开放衣服洗恩赐后，实战向防御可以优先寻找三个格挡和一个技能抵挡。只需要四金词条的玩家按这个方向凑齐即可；只需要三金的玩家同样优先选择格挡。" },
            ],
          },
          {
            id: "skills",
            title: "技能组",
            lead: "GVG 以净化之斩为默认思路，小规模场景再按队伍需求切换逐光或圣光。",
            image: "assets/singer-sequence8-pvp-gvg-03.webp",
            imageAlt: "歌颂者 PVP 推荐方案技能页截图，展示净化之斩、逐光与圣光净化",
            caption: "原攻略配图：歌颂者 PVP 推荐技能方案。",
            blocks: [
              { title: "GVG 技能组", text: "GVG 默认可以携带净化之斩。6v6 或其他小规模场景可以改带逐光，但需要同步调整非凡天赋。12v12 可以携带圣光，6v6 同样可以使用，最终按队伍需求和个人熟练度选择。" },
            ],
          },
          {
            id: "artifacts",
            title: "封印物选择",
            lead: "特殊封印物优先神灯，攻击封印物再根据暴击与战斗规模调整。",
            image: "assets/singer-sequence8-pvp-gvg-04.webp",
            imageAlt: "歌颂者封印物界面截图，展示攻击、防御与特化封印物方案",
            caption: "原攻略配图：封印物推荐方案界面。",
            blocks: [
              { title: "特殊封印物优先神灯", text: "特殊封印物优先推荐神灯，6v6 和 12v12 都很好用。当前战斗比较依赖 buff，因此神灯提供的技能刷新非常重要。" },
              { title: "攻击封印物按场景选择", text: "如果自身暴击较高，可以考虑公证书。6v6 场景也可以尝试斧子技能组，换下旋风斧；但暴风战斧容易让技能循环变得滞涩。GVG 场景推荐公证书与新焚决。" },
            ],
          },
          {
            id: "marionettes",
            title: "秘偶上阵",
            lead: "优先携带剥面人和头狼；破甲未达到目标时，改用星之虫守秘补足。",
            image: "assets/singer-sequence8-pvp-gvg-05.webp",
            imageAlt: "歌颂者秘偶界面截图，展示头狼与剥面人上阵方案",
            caption: "原攻略配图：秘偶上阵方案。",
            blocks: [
              { title: "常规上阵", text: "当前优先携带剥面人和头狼。" },
              { title: "破甲不足时替换头狼", text: "如果自身破甲没有达到 300 左右，就把头狼替换为星之虫守秘。" },
            ],
          },
          {
            id: "talent-switch",
            title: "天赋切换",
            lead: "技能组切换时同步调整非凡天赋，避免技能与天赋方向不一致。",
            image: "assets/singer-sequence8-pvp-gvg-06.webp",
            imageAlt: "歌颂者非凡天赋净化分支界面截图",
            caption: "原攻略配图：非凡天赋分支选择界面。",
            blocks: [
              { title: "逐光需要同步调整天赋", text: "6v6 或小规模场景改带逐光时，需要同步调整非凡天赋；技能组与天赋方向保持一致，实战循环会更稳定。" },
            ],
          },
          {
            id: "small-account",
            title: "小号 GVG 分支",
            lead: "序列 8 的新分支技能圣焰焚净，为小号玩家提供更容易成型的 GVG 方案。",
            image: "assets/singer-sequence8-pvp-gvg-07.webp",
            imageAlt: "歌颂者 PVP 推荐方案技能页截图，展示圣焰焚净技能",
            caption: "原攻略配图：小号 GVG 的圣焰焚净技能组。",
            blocks: [
              { title: "圣焰焚净降低成型门槛", text: "序列 8 开放了新的分支技能圣焰焚净。对于装备和属性还在成长中的小号玩家，这是 GVG 场景里的关键技能，可以降低对无暗和净化之斩的依赖，直接参与实体灼烧。" },
              { title: "以圣焰焚净为核心调整技能组", text: "技能组以圣焰焚净为核心，搭配辅助和控制技能。如果自身不容易存活，可以把旋风斧替换成盔甲。其余封印物和秘偶的选择，沿用上文的通用思路即可。" },
            ],
          },
        ],
      },
    },
    {
      id: "pve-notes",
      title: "歌颂者 PVE 团本配装与实战输出",
      summary: "更新序列 8 今日开放后的非凡天赋、圣光净化穿刺、属性优先级，以及封印物和秘偶的延续方案。",
      tags: ["PVE"],
      status: "已发布",
      updated: "2026年9月7日更新｜9月7日核验",
      featured: false,
      url: "guide-singer-pve.html",
      comboIds: ["pve-combo-ready"],
      videoIds: ["singer-pve-31k-dps-guide", "singer-pve-31k-dps-guide-douyin"],
      article: {
        intro: "本次更新补充序列 8 开放后的 PVE 调整：非凡天赋优先补穿刺，圣光净化的穿刺收益注意覆盖率与最低面板，其他属性、封印物和秘偶继续沿用上期攻略的思路。",
        published: "2026年9月7日",
        applicability: "公测首月｜老四 / 老五团本",
        sections: [
          {
            id: "talents",
            title: "序列 8 非凡天赋",
            lead: "今日开放序列 8 后，非凡天赋优先服务穿刺门槛；面板未达标时继续补穿刺。",
            image: "assets/singer-sequence8-pve-09-07-01.webp",
            imageAlt: "歌颂者序列 8 PVE 非凡天赋界面截图，展示圣裁分支",
            caption: "今日攻略配图：序列 8 PVE 非凡天赋方案。",
            blocks: [
              { title: "穿刺未达 1300 时继续补穿刺", text: "如果穿刺没有达到 1300，依然以穿刺为主选择天赋点，用来补足穿刺，不要过早转去堆其他输出属性。" },
              { title: "达到门槛后再调整属性", text: "穿刺达到 1300 后，再结合自身面板调整天赋和装备，把溢出的部分转移到其他收益更高的属性。" },
            ],
          },
          {
            id: "skills",
            title: "圣光净化与穿刺",
            lead: "圣光净化提供的穿刺不必担心溢出，但要同时关注技能覆盖率和实际面板底线。",
            image: "assets/singer-sequence8-pve-09-07-02.webp",
            imageAlt: "歌颂者序列 8 PVE 技能组截图，展示圣光净化方案",
            caption: "今日攻略配图：序列 8 PVE 技能组方案。",
            blocks: [
              { title: "圣光净化的穿刺可以计入面板", text: "序列 8 的圣光净化提供穿刺，不用担心因此溢出。如果可以调整穿刺，也可以把这部分收益补到其他属性上。" },
              { title: "注意覆盖率与最低穿刺", text: "圣光净化的技能覆盖率只有 50%，需要注意实际降低后的穿刺不要太低，尽量不要低于 1100。" },
            ],
          },
          {
            id: "thresholds",
            title: "属性优先级",
            lead: "其他属性要求继续沿用上期攻略；两项基础门槛达标后，按收益顺序补输出。",
            image: "assets/singer-sequence8-pve-09-07-03.webp",
            imageAlt: "歌颂者序列 8 PVE 角色面板与装备方案截图",
            caption: "今日攻略配图：序列 8 PVE 角色面板与装备方案。",
            blocks: [
              { title: "基础门槛先补穿刺与破防", text: "穿刺优先补至 1300；达到穿刺门槛后，再把破防补到上期攻略要求的目标值，之后再继续调整其他属性。" },
              { title: "收益顺序：怪物专攻 > 技能增强 > 攻击", text: "在基础门槛满足后，当前收益最高的属性顺序仍然是怪物专攻、技能增强、攻击，优先按这个顺序补齐。" },
            ],
          },
          {
            id: "artifacts",
            title: "封印物",
            lead: "封印物选择没有变化，继续按当前属性缺口补足；成型后再根据团本目标切换。",
            image: "assets/singer-sequence8-pve-09-07-04.webp",
            imageAlt: "歌颂者 PVE 封印物界面截图，展示幸运草、正义钱包与深红月冕",
            caption: "今日攻略配图：封印物推荐方案。",
            blocks: [
              { title: "缺哪部分就用哪部分补", text: "封印物沿用上期攻略的思路：根据自身缺少的属性选择对应封印物，不需要为了追求固定名单而牺牲当前面板。" },
              { title: "团本追伤再考虑神灯", text: "玩枪时优先保证核心输出封印物；关键属性未达标时先补足，进入团本后再根据战斗节奏考虑神灯刷新技能冷却。" },
            ],
          },
          {
            id: "marionettes",
            title: "秘偶",
            lead: "秘偶上阵没有变化，继续按属性缺口补足，优先保证怪物专攻与防御穿透方向。",
            image: "assets/singer-sequence8-pve-09-07-05.webp",
            imageAlt: "歌颂者 PVE 秘偶上阵界面截图，展示剥面人与星之虫守秘",
            caption: "今日攻略配图：秘偶上阵方案。",
            blocks: [
              { title: "沿用上期上阵思路", text: "封印物和秘偶上阵均无变化，仍然按上期攻略的思路选择，缺哪部分属性就用对应的秘偶补哪部分。" },
              { title: "属性不足时优先完成门槛", text: "常规上阵组合继续服务怪物专攻与防御穿透；如果关键属性尚未达标，先用能补足面板的秘偶，达到目标后再回到常规组合。" },
            ],
          },
        ],
      },
    },
  ],
  combos: [
    {
      id: "pvp-combo-ready",
      branch: "pvp",
      title: "歌颂者 PVP 连招码｜伤心游戏方案",
      scenario: "一键辅助：飓风斧、净化之斩、无暗之枪、秩序审判等。",
      version: "公测首月｜64装等三件套",
      updated: "2026年9月1日发布｜9月5日核验",
      code: "[[0dPSHJ0000002R1N0y0Kmyp12zQYT201twAG31E2HT4Dxkyk2V37S82xI61Q1a0BPA2wNekh2fDH8b1ovACd21F3XB1qgP0D1ovACd21FbdK1mcYWD0aoVIA2OMEJ128AruQ1Qzdbx01tUEl28AruQ1TGQz320fl7w1zCcF72fnp1k06KGRW1CF3Pd22WELp20CslH1CF3Pd22WEU525rsMw05otPU2fHNG32fmIQj2OMEJ128AruQ1Qzdbx01tUEl28AruQ1TGQz320fl7w284a7W37JDFc1viAP81mcRWb38Rbls1viAPA1mdoWz3lusaC37fGEc02uwiH2fDH8b1ovACd21F3XB1qgg3F1ovACd21FbdK1mcLy52OMEJ128AruQ1Qzdbx031sl128AruQ1TGQz31zqmRF01C4si000000]]",
      note: "复制该连招码后，在一键辅助界面右下角点击“导入”，即可使用来自“伤心游戏”的方案。",
      guideId: "field-manual",
      videoId: "singer-pvp-gvg-guide",
    },
    {
      id: "pve-combo-ready",
      branch: "pve",
      title: "歌颂者 PVE 连招码｜夏亚丶方案",
      scenario: "一键辅助：无暗之枪、人脉技能、秘偶技能、秩序审判等。",
      version: "公测首月｜老四 / 老五团本",
      updated: "2026年9月3日发布｜9月7日核验",
      code: "[[0Lyh4F0000002R1N0y0Kmyp133y8Xt0bM4So01t74u2dNRyk4BgxkQ2Qaav91TDMQq4Dqakz1qJTt81GUKp437AHN03Erafj2xF3pq2OMEJ128AruQ1Qzdbx01tUEl28AruQ1TGQz320fl7w1zVrfN2fnp1n06JzOU1CF3Pd22WELp20CspP1CF3Pd22WEU525rsJt2fDH8b1ovACd21F3XB1qgg3F1ovACd21FbdK1mcMAT2OMEJ128AruQ1Qzdbx01tUEl28AruQ1TGQz320fl7w284a7W37JDFc1viAP81mcRWb38Rbls1viAPA1mdoWz3lusaC37fGEc02uwiH2fDH8b1ovACd21F3XB1qgP0D1ovACd21FbdK1mcYWD0aoVIA2OMEJ128AruQ1Qzdbx01tUEl28AruQ1TGQz320fl7w1zVrfN2fnp1n06KGRW1CF3Pd22WELp20CslH1CF3Pd22WEU525rsMw05otOM2fHNG32flkKg2OMEJ128AruQ1Qzdbx01tUEl28AruQ1TGQz320fl7w1zVrfN2fnp1n06OMT30FCuhc000000]]",
      note: "复制该消息，在一键辅助界面右下角点击【导入】，即可一键使用来自【夏亚丶】的方案。",
      guideId: "pve-notes",
    },
  ],
  videos: [
    {
      id: "singer-pvp-gvg-guide",
      title: "《诡秘之主》歌颂者PVP/GVG保姆级攻略",
      platform: "哔哩哔哩",
      published: "2026年9月1日发布",
      description: "歌颂者 PVP / GVG 实战攻略视频。",
      url: "https://www.bilibili.com/video/BV1Lyth6QE5X/",
      guideId: "field-manual",
      comboIds: ["pvp-combo-ready"],
    },
    {
      id: "singer-pvp-gvg-guide-douyin",
      title: "《诡秘之主》歌颂者PVP/GVG保姆级攻略",
      platform: "抖音",
      published: "2026年9月1日发布",
      description: "歌颂者 PVP / GVG 实战攻略视频。",
      url: "https://v.douyin.com/YLJ0pR7n-nM/",
      guideId: "field-manual",
      comboIds: ["pvp-combo-ready"],
    },
    {
      id: "singer-pve-31k-dps-guide",
      title: "《诡秘之主》歌颂者3.1W秒伤PVE保姆级攻略",
      platform: "哔哩哔哩",
      published: "2026年9月3日发布",
      description: "歌颂者 PVE 实战攻略视频。",
      url: "https://www.bilibili.com/video/BV1HAbF6GEiP/",
      guideId: "pve-notes",
    },
    {
      id: "singer-pve-31k-dps-guide-douyin",
      title: "《诡秘之主》歌颂者3.1W秒伤PVE保姆级攻略",
      platform: "抖音",
      published: "2026年9月3日发布",
      description: "歌颂者 PVE 实战攻略视频。",
      url: "https://v.douyin.com/rvzFRftLf0s/",
      guideId: "pve-notes",
    },
  ],
});
