window.SITE_CONTENT = Object.freeze({
  profile: {
    name: "老洛MMO",
    specialty: "歌颂者 PVP / GVG / PVE 实战攻略",
    avatar: "assets/laoluo-avatar.jpg",
    shortBio: "专注歌颂者的图文实战判断、连招整理与 PVP / GVG / PVE 对局归档。",
    wechat: "Zephyrus1122",
  },
  version: {
    label: "公测首月版本",
    detail: "游戏官网当前下载信息为 Android 客户端 1.1.1、PC 启动器 1.1.43.0；不同平台编号不可互换。本站攻略按 9月初老四 / 老五团本与 64装等三件套阶段整理，最后核验于 2026年9月7日。",
  },
  platforms: [
    { name: "抖音", url: "https://v.douyin.com/MpvBDv7fusA/", note: "老洛MMO 抖音主页" },
    { name: "哔哩哔哩", url: "https://b23.tv/qdxbCnM", note: "老洛MMO B站主页" },
  ],
  guides: [
    {
      id: "strategic-server-prep",
      title: "歌颂者序列 8 战略服 PVP/GVG 备战攻略",
      summary: "独立整理 9 月 15 日战略服的 64 装等属性阈值、GVG 封印物、秘偶养成与技能组实战建议。",
      tags: ["PVP", "GVG", "战略服"],
      status: "已发布",
      updated: "2026年9月15日发布｜9月15日核验",
      featured: false,
      url: "guide-singer-strategic-server.html",
      comboIds: ["gvg-small-account-corpse"],
      article: {
        intro: "本攻略独立整理 9 月 15 日战略服开启前后的歌颂者备战重点，覆盖 64 装等 PVP 独珍、属性阈值、GVG 封印物、非凡物质、秘偶养成与技能组实战。",
        published: "2026年9月15日",
        applicability: "序列 8｜战略服 PVP / GVG",
        sections: [
          {
            id: "strategic-equipment",
            title: "战略服装备与属性",
            lead: "64 装等 PVP 独珍装先满足属性阈值，再把资源投向暴击、攻击与技能增强。",
            image: "assets/singer-sequence8-strategy-09-15-1.webp",
            imageAlt: "歌颂者序列 8 战略服角色面板与 PVP 装备方案截图",
            caption: "9 月 15 日战略服备战配图：64 装等 PVP 装备与属性面板。",
            blocks: [
              { title: "穿刺先到 1600 左右", text: "当前 PVP 不需要堆很高的穿刺，可以把穿刺资源让给其他属性。穿刺达到 1600 左右后，配合圣光净化的 buff 能到 2300 以上，已经足够应对当前环境。" },
              { title: "攻击与技能增强看比例", text: "当攻击和技能增强的比例大于 5：1 时，优先选择技能增强；少 1000 攻击换来 200 技能增强更划算。暴击在 buff 后超过 2000 时，大约可以达到 40%；1000—1900 多数处于 30% 区间，通常要到 2000 以上才有机会突破 40%。" },
              { title: "装备毕业方向", text: "装备可以按衣服独珍、戒指独珍、披风独珍，大橙武或小橙武，红胸针，百炼头、百炼项链和百炼鞋子的方向准备。" },
            ],
          },
          {
            id: "strategic-artifacts",
            title: "GVG 封印物与非凡物质",
            lead: "战略服开启六个孔位后，优先让封印物与非凡物质同时服务于 buff 覆盖和生存血量。",
            image: "assets/singer-sequence8-strategy-09-15-2.webp",
            imageAlt: "歌颂者战略服 GVG 封印物推荐方案截图，展示面具、皇冠与神灯",
            caption: "9 月 15 日战略服备战配图：GVG 封印物推荐方案。",
            blocks: [
              { title: "封印物仍选面具、皇冠、神灯", text: "神灯的技能刷新可以提高 buff 覆盖率，用来弥补面板数值；皇冠提供的霸体足够打两套循环；面具在被动触发时提供伤害上限。" },
              { title: "六个非凡物质的分配", text: "攻击部位选择天灾化身、攻击愚者；防御部位选择混乱行者、防御愚者；特殊部位选择攻击愚者，剩余一个四字稀有物质待后续攻略确定。" },
              { title: "防御位优先混乱行者", text: "混乱行者提供的是高额生命值，不是任何防御属性带来的收益。战略服上阵后总血量可以突破 30000，而当前带防御愚者约为 19000—20000，这额外的 10000 生命收益很难用其他防御属性替代。" },
            ],
          },
          {
            id: "strategic-marionettes",
            title: "秘偶上阵与养成",
            lead: "小丑加剥面人的组合同时服务混乱行者和最大生命百分比收益，是战略服血量目标的关键。",
            image: "assets/singer-sequence8-strategy-09-15-3.webp",
            imageAlt: "歌颂者战略服秘偶上阵界面截图，展示小丑与剥面人",
            caption: "9 月 15 日战略服备战配图：小丑与剥面人上阵方案。",
            blocks: [
              { title: "优先小丑加剥面人", text: "小丑上阵是为了配合混乱行者；小丑提供的最大生命百分比收益很高，也是预计把血量堆到 30000 的关键。小丑在 PVP 和 PVE 都属于通用级别，建议优先抽取并上阵。" },
              { title: "小铁与大橙武节点", text: "当前小铁数量为 50 块，下周也就是 9 月 21 日达到 62 块后，就可以兑换大橙武。" },
              { title: "提前囤装备强化石", text: "下周开启五阶强化，当前强化石大概率不够。每周体力买满并把箱子全部开满的账号，才可能刚好够用；否则要注意提前准备，避免当天无法第一时间强化到五阶。" },
            ],
          },
          {
            id: "strategic-skills",
            title: "战略服技能组与实战",
            lead: "大号重点练习逐日进退场和两套循环，把满技能爆发留给被动进场窗口。",
            image: "assets/singer-sequence8-strategy-09-15-4.webp",
            imageAlt: "歌颂者战略服 PVP 技能组方案截图，展示逐日、无暗之枪与圣光净化",
            caption: "9 月 15 日战略服备战配图：PVP 技能组与一键辅助方案。",
            blocks: [
              { title: "逐日进场离场打两套循环", text: "大号可以多练习用逐日进场、离场，完成两套循环和满技能爆发；同时留好技能，配合被动进场的时机把伤害打满。" },
            ],
          },
        ],
      },
    },
    {
      id: "singer-pve-09-15",
      title: "歌颂者 PVE 攻略｜9月15日更新",
      summary: "独立整理 9 月 15 日 PVE 的属性门槛、怪物专攻装备、秘偶、封印物与锤子技能组。",
      tags: ["PVE", "9月15日"],
      status: "已发布",
      updated: "2026年9月15日发布｜9月15日核验",
      featured: true,
      url: "guide-singer-pve-09-15.html",
      comboIds: ["pve-hammer-combo-ready"],
      article: {
        intro: "本攻略独立整理 9 月 15 日歌颂者 PVE 的装备、属性、秘偶、封印物与技能组选择。先满足破防、穿刺和暴击门槛，再按怪物专攻与输出稳定性完成取舍。",
        published: "2026年9月15日",
        applicability: "序列 8｜PVE｜9月15日更新",
        sections: [
          {
            id: "pve-0915-equipment",
            title: "PVE 装备与属性",
            lead: "破防、穿刺、暴击先过基础线，达标后以怪物专攻为主要方向。",
            image: "assets/singer-sequence8-pve-09-15-1.webp",
            imageAlt: "歌颂者序列 8 PVE 角色面板与装备方案截图",
            caption: "9 月 15 日 PVE 配图：独珍装备、百炼三件套与属性面板。",
            blocks: [
              { title: "先满足三项基础门槛", text: "推荐先把破防提高到 1300、穿刺提高到 1300，暴击达到 1000 左右。这里是当前 PVE 配装的参考线，具体仍要结合自身面板和副本需求调整。" },
              { title: "达标后优先怪物专攻", text: "当前独珍装备选择较多，满足基础属性后，装备取舍以补怪物专攻为主。推荐三件套部位选择百炼衣服、百炼戒指、百炼头；其余位置选择独珍鞋子、独珍护符、独珍武器、独珍披风和红胸针。" },
              { title: "最后补暴击与攻击", text: "基础属性和怪物专攻达标后，优先继续补暴击和攻击，让面板收益更稳定。" },
            ],
          },
          {
            id: "pve-0915-marionettes",
            title: "PVE 秘偶选择",
            lead: "优先星之虫守秘和星之虫咏；守秘练度不足时，小丑是更通用的替代方案。",
            image: "assets/singer-sequence8-pve-09-15-2.webp",
            imageAlt: "歌颂者 PVE 秘偶页面截图，展示星之虫秘偶方案",
            caption: "9 月 15 日 PVE 配图：星之虫秘偶选择参考。",
            blocks: [
              { title: "常规推荐星之虫守秘和星之虫咏", text: "PVE 秘偶优先考虑星之虫守秘和星之虫咏，作为当前副本输出与属性补足的常规组合。" },
              { title: "守秘练度不足时考虑小丑", text: "当前小丑满阶的伤害表现可以超过守秘。如果守秘练度不高，或者没有高阶的星之虫咏，可以考虑抽取小丑；小丑在 PVP 和 PVE 中都通用，无论上阵还是使用都能服务多种场景。" },
            ],
          },
          {
            id: "pve-0915-artifacts",
            title: "PVE 封印物选择",
            lead: "固定思路为蠕动、皇冠、日冕，下本时可按需求把日冕换成神灯。",
            image: "assets/singer-sequence8-pve-09-15-3.webp",
            imageAlt: "歌颂者 PVE 封印物页面截图，展示蠕动、皇冠与日冕方案",
            caption: "9 月 15 日 PVE 配图：封印物选择与升级方向。",
            blocks: [
              { title: "常规固定选择", text: "封印物常规选择以蠕动、皇冠、日冕为固定思路；进入副本时，可以考虑把日冕替换成神灯。" },
              { title: "二级封印物升级方向", text: "只玩 PVE 可以优先把蠕动升到 2 级；只玩 PVP 可以升面具；希望兼顾多个场景时，可以选择四叶草或日冕。" },
            ],
          },
          {
            id: "pve-0915-skills",
            title: "PVE 技能组",
            lead: "多数账号优先锤子，只有暴击很高时才考虑枪；输出稳定性优先。",
            image: "assets/singer-sequence8-pve-09-15-4.webp",
            imageAlt: "歌颂者 PVE 技能组页面截图，展示锤子与枪技能选择",
            caption: "9 月 15 日 PVE 配图：锤子技能组与一键辅助方案。",
            blocks: [
              { title: "默认优先锤子", text: "当前大部分账号都推荐带锤子，锤子的出伤更稳定；只有暴击很高的账号，才更适合考虑玩枪。" },
              { title: "避免誓约加锤子", text: "技能组选择时，注意不要使用誓约加锤子这种偏打桩的组合。优先选择能稳定完成输出循环的方案。" },
            ],
          },
        ],
      },
    },
    {
      id: "field-manual",
      title: "歌颂者序列 8 PVP GVG攻略",
      summary: "整理序列 8 阶段的天赋、装备、属性、防御、技能组、封印物与秘偶选择，并补充小号 GVG 的成型思路。",
      tags: ["PVP", "GVG"],
      status: "已发布",
      updated: "2026年9月7日发布｜9月7日核验",
      featured: false,
      url: "guide-singer-pvp-gvg.html",
      comboIds: ["pvp-combo-ready"],
      videoIds: ["singer-sequence8-pvp-pve-guide", "singer-sequence8-pvp-pve-guide-douyin"],
      article: {
        intro: "本攻略面向准备参与 PVP 与 GVG 的歌颂者序列 8 玩家，重点整理天赋、装备、属性、技能组、封印物和秘偶的选择。先按自身面板补齐短板，再根据战斗规模调整技能组。",
        published: "2026年9月7日",
        applicability: "序列 8｜PVP / GVG",
        sections: [
          {
            id: "talents",
            title: "天赋点",
            lead: "先完成序列 8 的扮演任务，再按自身面板选择有效属性更多的天赋节点。",
            image: "assets/singer-sequence8-pvp-gvg-01.webp",
            imageAlt: "歌颂者序列 8 非凡天赋界面截图，展示圣裁分支",
            caption: "原攻略配图：序列 8 非凡天赋推荐方案。",
            blocks: [
              { title: "先完成序列 8 扮演任务", text: "序列 8 开放后，先把序列 8 的扮演任务完成到 20%，拿够天赋点。当前阶段已经可以调整属性，不必再只看哪个节点分数高就带哪个。" },
              { title: "按面板短板选择节点", text: "点天赋前，先查看自身穿刺和格挡，优先补三项属性中更低的一项。还要注意目标属性在三个天赋节点中的排序：如果需要的属性排位较低，说明该节点提供的有效属性较少，换一个节点即可。" },
            ],
          },
          {
            id: "equipment",
            title: "装备选择",
            lead: "64 装等阶段先把独珍三件套穿齐，再根据面板补关键属性。",
            image: "assets/singer-sequence8-pvp-gvg-02.webp",
            imageAlt: "歌颂者序列 8 PVP 角色面板与装备方案截图",
            caption: "原攻略配图：序列 8 PVP 角色面板与装备方案。",
            blocks: [
              { title: "优先穿齐独珍三件套", text: "64 装等装备已经拿到不少时，优先把独珍三件套全部穿上，再根据自身面板补齐属性。装备选择的第一目标是让关键属性达标，不要为了单件装备的分数牺牲整体配置。" },
            ],
          },
          {
            id: "stats",
            title: "属性与防御方向",
            lead: "圣光进化提高增伤，穿刺与格挡按面板短板补齐，先满足 PVP / GVG 的实战阈值。",
            blocks: [
              { title: "圣光进化与增伤", text: "序列 8 开启圣光进化后，会获得额外 5% 增伤效果。暴击和穿刺的提升，会根据自身面板按比例放大，因此面板越高，进化带来的收益越明显。" },
              { title: "穿刺目标", text: "序列 8 打 PVP / GVG 不必把穿刺堆得过高，1800 以上即可；配合 buff 后，轻松达到约 2500，穿刺率可达到 80% 以上。" },
              { title: "格挡与技能抵挡", text: "今天开放衣服洗恩赐后，实战向防御可以优先寻找三个格挡和一个技能抵挡。只需要四金词条的玩家按这个方向凑齐即可；只需要三金的玩家同样优先选择格挡。" },
            ],
          },
          {
            id: "skills",
            title: "技能组",
            lead: "GVG 以净化之斩为默认思路，小规模场景再按队伍需求切换逐光或圣光。",
            image: "assets/singer-sequence8-pvp-gvg-03.webp",
            imageAlt: "歌颂者 PVP 推荐方案技能页截图，展示净化之斩、逐光与圣光净化",
            caption: "原攻略配图：歌颂者 PVP 推荐技能方案。",
            blocks: [
              { title: "GVG 技能组", text: "GVG 默认可以携带净化之斩。6v6 或其他小规模场景可以改带逐光，但需要同步调整非凡天赋。12v12 可以携带圣光，6v6 同样可以使用，最终按队伍需求和个人熟练度选择。" },
            ],
          },
          {
            id: "artifacts",
            title: "封印物选择",
            lead: "特殊封印物优先神灯，攻击封印物再根据暴击与战斗规模调整。",
            image: "assets/singer-sequence8-pvp-gvg-04.webp",
            imageAlt: "歌颂者封印物界面截图，展示攻击、防御与特化封印物方案",
            caption: "原攻略配图：封印物推荐方案界面。",
            blocks: [
              { title: "特殊封印物优先神灯", text: "特殊封印物优先推荐神灯，6v6 和 12v12 都很好用。当前战斗比较依赖 buff，因此神灯提供的技能刷新非常重要。" },
              { title: "攻击封印物按场景选择", text: "如果自身暴击较高，可以考虑公证书。6v6 场景也可以尝试斧子技能组，换下旋风斧；但暴风战斧容易让技能循环变得滞涩。GVG 场景推荐公证书与新焚决。" },
            ],
          },
          {
            id: "marionettes",
            title: "秘偶上阵",
            lead: "优先携带剥面人和头狼；破甲未达到目标时，改用星之虫守秘补足。",
            image: "assets/singer-sequence8-pvp-gvg-05.webp",
            imageAlt: "歌颂者秘偶界面截图，展示头狼与剥面人上阵方案",
            caption: "原攻略配图：秘偶上阵方案。",
            blocks: [
              { title: "常规上阵", text: "当前优先携带剥面人和头狼。" },
              { title: "破甲不足时替换头狼", text: "如果自身破甲没有达到 300 左右，就把头狼替换为星之虫守秘。" },
            ],
          },
          {
            id: "talent-switch",
            title: "天赋切换",
            lead: "技能组切换时同步调整非凡天赋，避免技能与天赋方向不一致。",
            image: "assets/singer-sequence8-pvp-gvg-06.webp",
            imageAlt: "歌颂者非凡天赋净化分支界面截图",
            caption: "原攻略配图：非凡天赋分支选择界面。",
            blocks: [
              { title: "逐光需要同步调整天赋", text: "6v6 或小规模场景改带逐光时，需要同步调整非凡天赋；技能组与天赋方向保持一致，实战循环会更稳定。" },
            ],
          },
          {
            id: "small-account",
            title: "小号 GVG 分支",
            lead: "序列 8 的新分支技能圣焰焚净，为小号玩家提供更容易成型的 GVG 方案。",
            image: "assets/singer-sequence8-pvp-gvg-07.webp",
            imageAlt: "歌颂者 PVP 推荐方案技能页截图，展示圣焰焚净技能",
            caption: "原攻略配图：小号 GVG 的圣焰焚净技能组。",
            blocks: [
              { title: "圣焰焚净降低成型门槛", text: "序列 8 开放了新的分支技能圣焰焚净。对于装备和属性还在成长中的小号玩家，这是 GVG 场景里的关键技能，可以降低对无暗和净化之斩的依赖，直接参与实体灼烧。" },
              { title: "以圣焰焚净为核心调整技能组", text: "技能组以圣焰焚净为核心，搭配辅助和控制技能。如果自身不容易存活，可以把旋风斧替换成盔甲。其余封印物和秘偶的选择，沿用上文的通用思路即可。" },
            ],
          },
        ],
      },
    },
    {
      id: "pve-notes",
      title: "歌颂者 PVE 团本配装与实战输出",
      summary: "更新序列 8 今日开放后的非凡天赋、圣光净化穿刺、属性优先级，以及封印物和秘偶的延续方案。",
      tags: ["PVE"],
      status: "已发布",
      updated: "2026年9月7日更新｜9月7日核验",
      featured: false,
      url: "guide-singer-pve.html",
      comboIds: ["pve-combo-ready"],
      videoIds: ["singer-sequence8-pvp-pve-guide", "singer-sequence8-pvp-pve-guide-douyin"],
      article: {
        intro: "本次更新补充序列 8 开放后的 PVE 调整：非凡天赋优先补穿刺，圣光净化的穿刺收益注意覆盖率与最低面板，其他属性、封印物和秘偶继续沿用上期攻略的思路。",
        published: "2026年9月7日",
        applicability: "公测首月｜老四 / 老五团本",
        sections: [
          {
            id: "talents",
            title: "序列 8 非凡天赋",
            lead: "今日开放序列 8 后，非凡天赋优先服务穿刺门槛；面板未达标时继续补穿刺。",
            image: "assets/singer-sequence8-pve-09-07-01.webp",
            imageAlt: "歌颂者序列 8 PVE 非凡天赋界面截图，展示圣裁分支",
            caption: "今日攻略配图：序列 8 PVE 非凡天赋方案。",
            blocks: [
              { title: "穿刺未达 1300 时继续补穿刺", text: "如果穿刺没有达到 1300，依然以穿刺为主选择天赋点，用来补足穿刺，不要过早转去堆其他输出属性。" },
              { title: "达到门槛后再调整属性", text: "穿刺达到 1300 后，再结合自身面板调整天赋和装备，把溢出的部分转移到其他收益更高的属性。" },
            ],
          },
          {
            id: "skills",
            title: "圣光净化与穿刺",
            lead: "圣光净化提供的穿刺不必担心溢出，但要同时关注技能覆盖率和实际面板底线。",
            image: "assets/singer-sequence8-pve-09-07-02.webp",
            imageAlt: "歌颂者序列 8 PVE 技能组截图，展示圣光净化方案",
            caption: "今日攻略配图：序列 8 PVE 技能组方案。",
            blocks: [
              { title: "圣光净化的穿刺可以计入面板", text: "序列 8 的圣光净化提供穿刺，不用担心因此溢出。如果可以调整穿刺，也可以把这部分收益补到其他属性上。" },
              { title: "注意覆盖率与最低穿刺", text: "圣光净化的技能覆盖率只有 50%，需要注意实际降低后的穿刺不要太低，尽量不要低于 1100。" },
            ],
          },
          {
            id: "thresholds",
            title: "属性优先级",
            lead: "其他属性要求继续沿用上期攻略；两项基础门槛达标后，按收益顺序补输出。",
            image: "assets/singer-sequence8-pve-09-07-03.webp",
            imageAlt: "歌颂者序列 8 PVE 角色面板与装备方案截图",
            caption: "今日攻略配图：序列 8 PVE 角色面板与装备方案。",
            blocks: [
              { title: "基础门槛先补穿刺与破防", text: "穿刺优先补至 1300；达到穿刺门槛后，再把破防补到上期攻略要求的目标值，之后再继续调整其他属性。" },
              { title: "收益顺序：怪物专攻 > 技能增强 > 攻击", text: "在基础门槛满足后，当前收益最高的属性顺序仍然是怪物专攻、技能增强、攻击，优先按这个顺序补齐。" },
            ],
          },
          {
            id: "artifacts",
            title: "封印物",
            lead: "封印物选择没有变化，继续按当前属性缺口补足；成型后再根据团本目标切换。",
            image: "assets/singer-sequence8-pve-09-07-04.webp",
            imageAlt: "歌颂者 PVE 封印物界面截图，展示幸运草、正义钱包与深红月冕",
            caption: "今日攻略配图：封印物推荐方案。",
            blocks: [
              { title: "缺哪部分就用哪部分补", text: "封印物沿用上期攻略的思路：根据自身缺少的属性选择对应封印物，不需要为了追求固定名单而牺牲当前面板。" },
              { title: "团本追伤再考虑神灯", text: "玩枪时优先保证核心输出封印物；关键属性未达标时先补足，进入团本后再根据战斗节奏考虑神灯刷新技能冷却。" },
            ],
          },
          {
            id: "marionettes",
            title: "秘偶",
            lead: "上阵组合优先服务怪物专攻与防御穿透；当前 PVE 实际上阵的是星之虫守秘和星之虫泳。",
            image: "assets/singer-pve-marionettes.webp",
            imageAlt: "歌颂者 PVE 秘偶上阵界面截图，展示星之虫守秘和星之虫泳的上阵方案",
            caption: "PVE 秘偶截图：星之虫守秘和星之虫泳的上阵参考。",
            blocks: [
              { title: "实际 PVE 上阵：星之虫守秘和星之虫泳", text: "当前 PVE 常规推荐星之虫守秘和星之虫泳，作为 PVE 上阵组合。" },
              { title: "破防未达标时优先补忽视防御", text: "若破防尚未达到目标，可将星之虫泳替换为提供忽视防御的上阵秘偶，先完成属性阈值，再回到常规组合。" },
            ],
          },
        ],
      },
    },
  ],
  combos: [
    {
      id: "pvp-combo-ready",
      branch: "pvp",
      title: "歌颂者 PVP 连招码｜夏亚丶方案",
      scenario: "一键辅助：无暗之枪、飓风斧、净化之斩、秩序审判等。",
      version: "公测首月｜64装等三件套",
      updated: "2026年9月7日更新｜9月7日核验",
      code: "[[3mJ2Fz0000002R1N0y0Kmyp133y8Y40bM4So01t74u2dNRyk4BgxkQ2Qaav91TDNAG4Dqakz1qFibL2qdaUF1CF3Pd22WEU525rsMw05otPU37JDFc1viAP81mcRWb2fHNG32fmIQj2OMVM328AruQ1TGQz320fl7w1zFONN1ovACd21F3XB1qgNM238Rbls1viAPA1mdoWz3lusaC2OMEJ128AruQ1Qzdbx01mQJ008aumb2fDHCj1ovACd21FbdK1mcYWD0aqdpK1CF3Pd22WELp20Csks2OMVM328AruQ1TGQz320fl7w1zNdqL1ovACd21F3XB1qgNI92fmRmi01mPJT1CF3Pd22WEU525rsMw05ot8E37JDFc1viAP81mcRWb2gLfiz1ovACd21FbdK1mcYWD0aoZII1CF3Pd22WELp20Cskr2fHV5O02IJyU38Rbls1viAPA1mdoWz0K3XVr28AruQ1Qzdbx02v4sl1CF3Pd22WEU525rsJw37JDFc1viAP81mcRWc2fHNFy2fnwSQ2OMVM328AruQ1TGQz31zqn1l1ovACd21F3XB1qgeLB2fo68605otuc01mgMV1CF3Pd22WEU525rsMw05otPU37JDFc1viAP81mcRWb2fHNG32fmIQz1vDoZR]]",
      note: "复制该消息，在一键辅助界面右下角点击【导入】，一键使用来自【夏亚丶】的方案。",
      guideId: "field-manual",
      videoId: "singer-pvp-gvg-guide",
    },
    {
      id: "pve-combo-ready",
      branch: "pve",
      title: "歌颂者 PVE 连招码｜夏亚丶方案",
      scenario: "一键辅助：无暗之枪、人脉技能、秘偶技能、秩序审判等。",
      version: "公测首月｜老四 / 老五团本",
      updated: "2026年9月3日发布｜9月7日核验",
      code: "[[0Lyh4F0000002R1N0y0Kmyp133y8Xt0bM4So01t74u2dNRyk4BgxkQ2Qaav91TDMQq4Dqakz1qJTt81GUKp437AHN03Erafj2xF3pq2OMEJ128AruQ1Qzdbx01tUEl28AruQ1TGQz320fl7w1zVrfN2fnp1n06JzOU1CF3Pd22WELp20CspP1CF3Pd22WEU525rsJt2fDH8b1ovACd21F3XB1qgg3F1ovACd21FbdK1mcMAT2OMEJ128AruQ1Qzdbx01tUEl28AruQ1TGQz320fl7w284a7W37JDFc1viAP81mcRWb38Rbls1viAPA1mdoWz3lusaC37fGEc02uwiH2fDH8b1ovACd21F3XB1qgP0D1ovACd21FbdK1mcYWD0aoVIA2OMEJ128AruQ1Qzdbx01tUEl28AruQ1TGQz320fl7w1zVrfN2fnp1n06KGRW1CF3Pd22WELp20CslH1CF3Pd22WEU525rsMw05otOM2fHNG32flkKg2OMEJ128AruQ1Qzdbx01tUEl28AruQ1TGQz320fl7w1zVrfN2fnp1n06OMT30FCuhc000000]]",
      note: "复制该消息，在一键辅助界面右下角点击【导入】，即可一键使用来自【夏亚丶】的方案。",
      guideId: "pve-notes",
    },
    {
      id: "pve-hammer-combo-ready",
      branch: "pve-hammer",
      title: "PVE 锤子连招码｜夏亚丶方案",
      scenario: "一键辅助：惩戒、秩序审判、圣光净化、惩戒等。",
      version: "公测首月｜PVE 锤子",
      updated: "2026年9月13日新增｜待补充核验日期",
      code: "[[2sLkdn0000002R1N0y0Kmyp133y8Xt0bMswW01t74u2dNRyk4BgxkQ2QaaFk2xF3ty2OMEJ128AruQ1Qzdbx01tUEl28AruQ1TGQz320fl7w1zT7B32fnp1n043CLy1CF3Pd22WELp20CslH1CF3Pd22WEU525rsMw05otuc2gLfer1ovACd21F3XB1qgP0D1ovACd21FbdK1mcYWD0aoXI12fHUkk095ay237JDFc1viAP81mcRWb38Rbls1viAPA1mdoWz3lusaC3UNAdm08auyx2fDH8b1ovACd21F3XB1qgg3F1ovACd21FbdK1mcMAT2OMEJ128AruQ1Qzdbx031sl128AruQ1TGQz31zpwEU37JDFc1viAP81mcRWb38Rbls1viAPA1mdoWz3lusaC2OFhTm1CF3Pd22WELp20CslH1CF3Pd22WEU525rsMw05otPK2fHNG32fmZLV2OMEJ128AruQ1Qzdbx01tUEl28AruQ1TGQz320fl7w1zFMnK37JDFc1viAP81mcRWb38Rbls1viAPA1mdoWz3lusaC3UNAdm08auyx2xGY0f21dVkU1GUL1I30GXgm000000]]",
      note: "复制该消息，在一键辅助界面右下角点击【导入】，一键使用来自【夏亚丶】的方案。",
    },
    {
      id: "gvg-small-account-corpse",
      branch: "gvg-small-account",
      title: "小号 GVG 烧尸体｜夏亚丶方案",
      scenario: "一键辅助：惩戒、人脉技能、秘偶技能、秩序审判等。",
      version: "公测首月｜小号 GVG",
      updated: "2026年9月10日发布｜待补充核验日期",
      code: "[[29Ig4p0000002R1N0y0Kmyp137KqfP0bLnHP4CbHm536tz5T4BhU2O3NipKm2xF3ty2OMEJ128AruQ1Qzdbx01tUEl28AruQ1TGQz320fl7w1zT7B32fnp1n043CLy1CF3Pd22WELp20CspP1CF3Pd22WEU525rsJt2fDH8b1ovACd21F3XB1qgg3F1ovACd21FbdK1mcMAT2OMEJ128AruQ1Qzdbx01tUEl28AruQ1TGQz320fl7w284a3O37JDFc1viAP81mcRWb38Rbls1viAPA1mdoWz3lusaC3J1CRe1CF3Pd22WELp20CslH1CF3Pd22WEU525rsMw05otOW2gLfer1ovACd21F3XB1qgP0D1ovACd21FbdK1mcYWD0aoYcb2fHV5O03QAOg37JDFc1viAP81mcRWb38Rbls1viAPA1mdoWz3lusaC37fWI61CF3Pd22WELp20CslH1CF3Pd22WEU525rsMw05otPA2fHNFx2fqxzm2OMEJ128AruQ1Qzdbx01tUEl28AruQ1TGQz320fl7w1zT7B32fnp1n047Znu1Iznsm4Chdgr2RcReD01qm5w0FCuhc000000]]",
      note: "复制该消息，在一键辅助界面右下角点击【导入】，一键使用来自【夏亚丶】的方案。",
      guideId: "strategic-server-prep",
    },
  ],
  videos: [
    {
      id: "singer-sequence8-pvp-pve-guide",
      title: "《诡秘之主》歌颂者序列8PVP/PVE攻略+属性计算器！",
      platform: "哔哩哔哩",
      published: "2026年9月7日发布",
      description: "歌颂者序列 8 PVP / PVE 全攻略，包含属性计算器。",
      url: "https://www.bilibili.com/video/BV1YRbT6SEse/?share_source=copy_web&vd_source=c348ee5920a32bafacceb4ed06c2dec7",
      guideIds: ["field-manual", "pve-notes"],
      comboIds: ["pvp-combo-ready", "pve-combo-ready"],
    },
    {
      id: "singer-sequence8-pvp-pve-guide-douyin",
      title: "《诡秘之主》歌颂者序列8PVP/PVE攻略+属性计算器！",
      platform: "抖音",
      published: "2026年9月7日发布",
      description: "歌颂者序列 8 PVP / PVE 全攻略，包含属性计算器。",
      url: "https://v.douyin.com/kuDJX5OcEZU/",
      guideIds: ["field-manual", "pve-notes"],
      comboIds: ["pvp-combo-ready", "pve-combo-ready"],
    },
    {
      id: "singer-pvp-gvg-guide",
      title: "《诡秘之主》歌颂者PVP/GVG保姆级攻略",
      platform: "哔哩哔哩",
      published: "2026年9月1日发布",
      description: "歌颂者 PVP / GVG 实战攻略视频。",
      url: "https://www.bilibili.com/video/BV1Lyth6QE5X/",
    },
    {
      id: "singer-pvp-gvg-guide-douyin",
      title: "《诡秘之主》歌颂者PVP/GVG保姆级攻略",
      platform: "抖音",
      published: "2026年9月1日发布",
      description: "歌颂者 PVP / GVG 实战攻略视频。",
      url: "https://v.douyin.com/YLJ0pR7n-nM/",
    },
    {
      id: "singer-pve-31k-dps-guide",
      title: "《诡秘之主》歌颂者3.1W秒伤PVE保姆级攻略",
      platform: "哔哩哔哩",
      published: "2026年9月3日发布",
      description: "歌颂者 PVE 实战攻略视频。",
      url: "https://www.bilibili.com/video/BV1HAbF6GEiP/",
    },
    {
      id: "singer-pve-31k-dps-guide-douyin",
      title: "《诡秘之主》歌颂者3.1W秒伤PVE保姆级攻略",
      platform: "抖音",
      published: "2026年9月3日发布",
      description: "歌颂者 PVE 实战攻略视频。",
      url: "https://v.douyin.com/rvzFRftLf0s/",
    },
  ],
});
