window.SITE_CONTENT = Object.freeze({
  profile: {
    name: "老洛MMO",
    specialty: "歌颂者 PVP / GVG / PVE 实战攻略",
    avatar: "assets/laoluo-avatar.jpg",
    shortBio: "专注歌颂者的图文实战判断、连招整理与 PVP / GVG / PVE 对局归档。",
    wechat: "Zephyrus1122",
  },
  version: {
    label: "公测首月版本",
    detail: "游戏官网当前下载信息为 Android 客户端 1.1.1、PC 启动器 1.1.43.0；不同平台编号不可互换。本站攻略按 9月初老四 / 老五团本与 64装等三件套阶段整理，最后核验于 2026年9月5日。",
  },
  platforms: [
    { name: "抖音", url: "https://v.douyin.com/MpvBDv7fusA/", note: "老洛MMO 抖音主页" },
    { name: "哔哩哔哩", url: "https://b23.tv/qdxbCnM", note: "老洛MMO B站主页" },
  ],
  guides: [
    {
      id: "field-manual",
      title: "歌颂者 PVP / GVG 配装与团队职责",
      summary: "围绕 64 装等三件套、属性取向、技能替换、封印物、秘偶与非凡天赋整理的实战配装参考。",
      tags: ["PVP", "GVG"],
      status: "已发布",
      updated: "2026年9月1日发布｜9月5日核验",
      featured: false,
      url: "guide-singer-pvp-gvg.html",
      comboIds: ["pvp-combo-ready"],
      videoIds: ["singer-pvp-gvg-guide", "singer-pvp-gvg-guide-douyin"],
      article: {
        intro: "本篇按公测首月的 64装等三件套阶段整理。重点不是固定照搬，而是根据 6V6、GVG 与账号养成情况，在输出、功能和团队职责之间做取舍。",
        published: "2026年9月1日",
        applicability: "公测首月｜64装等三件套阶段",
        sections: [
          {
            id: "setup",
            title: "装备与属性",
            lead: "先确定套装和基础属性，再根据自身养成决定继续堆输出，还是把资源留给团队功能。",
            image: "assets/singer-pvp-gvg-character.webp",
            imageAlt: "歌颂者 PVP 角色面板与装备方案截图",
            caption: "原始配装截图：64 装等 PVP 三件套与角色属性面板。",
            blocks: [
              { title: "三件套优先，遇到胸针冲突可先保两件", text: "64 装等开放三件套后，优先凑齐三件套效果。如果其中一件与胸针或红色胸针冲突，暂时只保留两件套也可以，先保证当前方案能稳定成型。" },
              { title: "属性按输出与生存分开看", text: "输出属性以穿刺、暴击、攻击为主。穿刺建议至少达到 1500，再继续补攻击和暴击。防御端以格挡为主，格挡越高，越能承担持续换血和拉扯中的压力。" },
            ],
          },
          {
            id: "skills",
            title: "技能组与团队职责",
            lead: "6V6 与 GVG 的技能选择不同，歌颂者的价值也不应只按个人输出计算。",
            image: "assets/singer-pvp-gvg-skills.webp",
            imageAlt: "歌颂者 PVP 技能组与封印物栏截图",
            caption: "原始技能组截图：可参考 6V6 方案中的核心主动技能与封印物栏位。",
            blocks: [
              { title: "逐日只作为 6V6 标配", text: "逐日可作为 6V6 的固定选择；其他 GVG 场景更建议替换为净化之斩。这样能把技能栏留给更符合团战节奏的功能。" },
              { title: "净化之斩的核心是阻断战复", text: "歌颂者具备净化尸体的能力，常被称为“烧尸体”。目标是阻止对方治疗职业通过战复迅速补回即时战力。势力战地图较大，被净化后从复活点重返前线需要时间，因此除了输出，也要主动关注残局里的尸体处理。" },
              { title: "养成不足时，优先做功能位", text: "人脉与秘偶技能当前优先考虑梦魇冲击和隐匿刺击。若技能等级暂时不够，人脉技能可换成蘑菇，隐匿刺击可换为控制技能。账号基础较弱时，比起硬追输出，更推荐多带控制、积极烧尸体，为团队创造收益。" },
            ],
          },
          {
            id: "artifacts",
            title: "封印物",
            lead: "常规方案按攻击、防御和特化三条线选择；面具流属于需要操作支撑的变体。",
            image: "assets/singer-pvp-gvg-sealed-artifacts.webp",
            imageAlt: "歌颂者推荐封印物截图，包含幸运草、正义钱包和深红月冕",
            caption: "原始封印物截图：常规推荐为幸运草、正义钱包与深红月冕。",
            blocks: [
              { title: "常规搭配", text: "攻击封印物推荐幸运草；面具也可选择，但更依赖个人操作。防御封印物推荐正义钱包，特化封印物选择深红月冕。" },
              { title: "小号与 6V6 的替代思路", text: "养成较低时，攻击可带斧子，防御带纸人，特化带布偶。6V6 也可以沿用截图中的方案；另一套面具加神灯流兼顾爆发、技能刷新和保命，但更适合有愚者配合、能抵消神灯负面效果的队伍。" },
            ],
          },
          {
            id: "marionettes",
            title: "秘偶",
            lead: "先确定上阵收益，再规划抽取顺序，避免把资源分散到短期难以使用的秘偶上。",
            image: "assets/singer-pvp-gvg-marionettes.webp",
            imageAlt: "歌颂者秘偶界面截图，展示剥面人与星之虫守秘",
            caption: "原始秘偶截图：上阵选择剥面人与星之虫守秘。",
            blocks: [
              { title: "上阵与抽取顺序", text: "上阵推荐剥面人与星之虫守秘，这两个组合可提供四攻。抽取优先考虑剥面人、星之虫守秘、异化赛琳娜；赛琳娜作为主要使用对象时，达到 20 阶后可解锁第三阶段。" },
            ],
          },
          {
            id: "talents",
            title: "非凡天赋",
            lead: "天赋选择以场景与账号能力为准，低养成时统一走更稳定的团队向配置。",
            image: "assets/singer-pvp-gvg-talents.webp",
            imageAlt: "歌颂者非凡天赋界面截图，展示领歌与圣裁分支",
            caption: "原始非凡天赋截图：领歌为群伤辅助方向，圣裁为单体爆发方向。",
            blocks: [
              { title: "6V6 带领歌，其余场景带圣裁", text: "6V6 可以统一带领歌；其他场景更建议选择圣裁。养成较低的账号则可以全部统一带领歌，以更稳定的功能收益参与团队。" },
            ],
          },
        ],
      },
    },
    {
      id: "pve-notes",
      title: "歌颂者 PVE 团本配装与实战输出",
      summary: "围绕老四 / 老五团本的属性门槛、独珍构筑、实战技能组、封印物、秘偶与圣裁天赋整理的 PVE 参考。",
      tags: ["PVE"],
      status: "已发布",
      updated: "2026年9月3日发布｜9月5日核验",
      featured: true,
      url: "guide-singer-pve.html",
      comboIds: ["pve-combo-ready"],
      videoIds: ["singer-pve-31k-dps-guide", "singer-pve-31k-dps-guide-douyin"],
      article: {
        intro: "本篇按公测首月的老四 / 老五团本阶段整理。先补齐属性门槛，再围绕多动 Boss 的实战覆盖调整独珍、技能组与封印物，而不是只追求打桩面板。",
        published: "2026年9月3日",
        applicability: "公测首月｜老四 / 老五团本",
        sections: [
          {
            id: "thresholds",
            title: "团本门槛与属性优先级",
            lead: "本篇以老四 / 老五团本的 1.8w 秒伤作为参考门槛，实际进组要求以所在团队为准。属性顺序比盲目堆单项面板更重要。",
            image: "assets/singer-pve-character.webp",
            imageAlt: "歌颂者 PVE 角色面板与装备方案截图",
            caption: "原始 PVE 配装截图：角色面板与冒险三件套方案。",
            blocks: [
              { title: "先把穿刺补至 1300", text: "穿刺不足 1300 时，优先用现有资源补满。这一阶段的穿刺收益最高，不建议提前把资源分散到其他输出属性。" },
              { title: "再补破防，再堆输出属性", text: "穿刺达到 1300 后，将破防补到 1300。两项都达标后，按怪物专攻、技能增强、攻击的顺序继续堆叠。" },
            ],
          },
          {
            id: "skills",
            title: "独珍构筑与实战技能组",
            lead: "独珍优先补当前关键属性缺口；技能组的标准应是多动 Boss 中的实战覆盖，而不只是打桩数字。",
            image: "assets/singer-pve-skills.webp",
            imageAlt: "歌颂者 PVE 技能组与封印物栏截图",
            caption: "原始 PVE 方案截图：实战技能组与封印物栏位参考。",
            blocks: [
              { title: "独珍按当前缺口补属性", text: "独珍装备的效果应服务于当前构筑：缺什么属性，就优先用带对应加成的独珍补齐，而不是固定照搬单一装备名单。" },
              { title: "不要把纯打桩流当作多动 Boss 的默认解", text: "原攻略将惩戒加太阳誓约定位为偏打桩的方案，双吃太阳誓约收益时数字更高，但多动 Boss 会持续丢失伤害。团本实战更应选择能稳定覆盖战斗过程的技能组。" },
              { title: "三阶小丑优先于放逐", text: "秘偶技能选择小丑。原攻略指出，小丑达到 20 级并开启三阶后，伤害已高于放逐。" },
            ],
          },
          {
            id: "artifacts",
            title: "封印物",
            lead: "枪流优先保证核心伤害封印物；属性未达标与团本追伤时，各有不同的替代选择。",
            image: "assets/singer-pve-sealed-artifacts.webp",
            imageAlt: "歌颂者 PVE 封印物界面截图",
            caption: "原始 PVE 封印物截图：根据属性缺口与团本目标调整选择。",
            blocks: [
              { title: "枪流首推四叶草", text: "玩枪时优先选择四叶草，作为常规输出封印物。" },
              { title: "属性不足补蠕动的饥饿，团本可换神灯", text: "关键属性未达标时，用蠕动的饥饿补足。进入团本后，特殊封印物可换成神灯，通过刷新 CD 追求更高伤害。" },
            ],
          },
          {
            id: "marionettes",
            title: "秘偶",
            lead: "上阵组合优先服务怪物专攻与防御穿透；属性尚未达标时，允许为关键阈值做替换。",
            image: "assets/singer-pve-marionettes.webp",
            imageAlt: "歌颂者 PVE 秘偶上阵界面截图",
            caption: "原始 PVE 秘偶截图：星之虫泳与星之虫守秘的上阵参考。",
            blocks: [
              { title: "常规上阵：星之虫泳与星之虫守秘", text: "常规推荐星之虫泳与星之虫守秘，作为 PVE 上阵组合。" },
              { title: "破防未达标时优先补忽视防御", text: "若破防尚未达到目标，将星之虫泳替换为提供忽视防御的上阵秘偶，先完成属性阈值再回到常规组合。" },
            ],
          },
          {
            id: "talents",
            title: "非凡天赋",
            lead: "PVE 输出方向选择圣裁，和前面的实战技能组、属性优先级保持一致。",
            image: "assets/singer-pve-talents.webp",
            imageAlt: "歌颂者 PVE 非凡天赋界面截图，展示圣裁分支",
            caption: "原始 PVE 非凡天赋截图：圣裁为单体爆发方向。",
            blocks: [
              { title: "选择圣裁", text: "PVE 天赋选择圣裁，作为团本单体输出方向。" },
            ],
          },
        ],
      },
    },
  ],
  combos: [
    {
      id: "pvp-combo-ready",
      branch: "pvp",
      title: "歌颂者 PVP 连招码｜伤心游戏方案",
      scenario: "一键辅助：飓风斧、净化之斩、无暗之枪、秩序审判等。",
      version: "公测首月｜64装等三件套",
      updated: "2026年9月1日发布｜9月5日核验",
      code: "[[0dPSHJ0000002R1N0y0Kmyp12zQYT201twAG31E2HT4Dxkyk2V37S82xI61Q1a0BPA2wNekh2fDH8b1ovACd21F3XB1qgP0D1ovACd21FbdK1mcYWD0aoVIA2OMEJ128AruQ1Qzdbx01tUEl28AruQ1TGQz320fl7w1zCcF72fnp1k06KGRW1CF3Pd22WELp20CslH1CF3Pd22WEU525rsMw05otPU2fHNG32fmIQj2OMEJ128AruQ1Qzdbx01tUEl28AruQ1TGQz320fl7w284a7W37JDFc1viAP81mcRWb38Rbls1viAPA1mdoWz3lusaC37fGEc02uwiH2fDH8b1ovACd21F3XB1qgg3F1ovACd21FbdK1mcLy52OMEJ128AruQ1Qzdbx031sl128AruQ1TGQz31zqmRF01C4si000000]]",
      note: "复制该连招码后，在一键辅助界面右下角点击“导入”，即可使用来自“伤心游戏”的方案。",
      guideId: "field-manual",
      videoId: "singer-pvp-gvg-guide",
    },
    {
      id: "pve-combo-ready",
      branch: "pve",
      title: "歌颂者 PVE 连招码｜夏亚丶方案",
      scenario: "一键辅助：无暗之枪、人脉技能、秘偶技能、秩序审判等。",
      version: "公测首月｜老四 / 老五团本",
      updated: "2026年9月3日发布｜9月5日核验",
      code: "[[0UEXX30000002R1N0y0Kmyp133y8Xt0bM4So01t74u2dNRyk4BgxkQ2Qaav91TDMQq4Dqakz1vDyQW3BuuBh0bM4So0bM3vs4GCI531p5NkQ38Rbls1viAPA1mdoWz3lusaC3fpuj528AruQ1Qzdbx01mQJ008auyz2fDHCj1ovACd21FbdK1mcLyU1CF3Pd22WELp20Csoz2OMVM328AruQ1TGQz31zqn1l1ovACd21F3XB1qgeKw38Rbls1viAPA1mdoWz3lusaK1VrFKd28AruQ1Qzdbx01mgMV1CF3Pd22WEU525rsMw05otP037JDFc1viAP81mcRWb2fHNFy2fnwSP2OMVM328AruQ1TGQz320fl7w1zFONN1ovACd21F3XB1qgNM238Rbls1viAPA1mdoWz3lusaC3fpuj528AruQ1Qzdbx01mQJ008auyz2gLfiz1ovACd21FbdK1mcYWD0aoUdG1CF3Pd22WELp20Cskr2fHV5O019eTK38Rbls1viAPA1mdoWz3lusaC3fpuj528AruQ1Qzdbx01mQJ008auyz0FCuhc000000]]",
      note: "复制该连招码后，在一键辅助界面右下角点击“导入”，即可使用来自“夏亚丶”的方案。",
      guideId: "pve-notes",
      videoId: "singer-pve-31k-dps-guide",
    },
  ],
  videos: [
    {
      id: "singer-pvp-gvg-guide",
      title: "《诡秘之主》歌颂者PVP/GVG保姆级攻略",
      platform: "哔哩哔哩",
      published: "2026年9月1日发布",
      description: "歌颂者 PVP / GVG 实战攻略视频。",
      url: "https://www.bilibili.com/video/BV1Lyth6QE5X/",
      guideId: "field-manual",
      comboIds: ["pvp-combo-ready"],
    },
    {
      id: "singer-pvp-gvg-guide-douyin",
      title: "《诡秘之主》歌颂者PVP/GVG保姆级攻略",
      platform: "抖音",
      published: "2026年9月1日发布",
      description: "歌颂者 PVP / GVG 实战攻略视频。",
      url: "https://v.douyin.com/YLJ0pR7n-nM/",
      guideId: "field-manual",
      comboIds: ["pvp-combo-ready"],
    },
    {
      id: "singer-pve-31k-dps-guide",
      title: "《诡秘之主》歌颂者3.1W秒伤PVE保姆级攻略",
      platform: "哔哩哔哩",
      published: "2026年9月3日发布",
      description: "歌颂者 PVE 实战攻略视频。",
      url: "https://www.bilibili.com/video/BV1HAbF6GEiP/",
      guideId: "pve-notes",
      comboIds: ["pve-combo-ready"],
    },
    {
      id: "singer-pve-31k-dps-guide-douyin",
      title: "《诡秘之主》歌颂者3.1W秒伤PVE保姆级攻略",
      platform: "抖音",
      published: "2026年9月3日发布",
      description: "歌颂者 PVE 实战攻略视频。",
      url: "https://v.douyin.com/rvzFRftLf0s/",
      guideId: "pve-notes",
      comboIds: ["pve-combo-ready"],
    },
  ],
});
